global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "lysergic-backend"
    static_configs:
      - targets: ["lysergic.kaizenklass.xyz"]
    scheme: "https"
    metrics_path: "/metrics"
    scrape_interval: 5s
